// Keys are stored in DB; labels are translated in i18n.jsx
export const CITY_KEYS = [
  "jerusalem",
  "nazareth",
  "haifa",
  "jaffa",
  "acre",
  "ramla",
  "lod",
  "tamra",
  "shfaram",
  "umm_al_fahm",
  "baqa_al_gharbiyye",
  "qalansawe",
  "tayibe",
  "kafr_qasim",
  "kafr_kanna",
  "majd_al_krum",
  "sakhnin",
  "arrabe",
  "deir_hanna",
  "yirka",
  "judeide_maker",
  "kafr_yasif",
  "rahat",
  "beer_sheva",
  "tel_aviv",
  "netanya",
  "petah_tikva",
  "rishon_lezion",
  "ashdod",
  "ashkelon",
  "bat_yam",
  "herzliya",
  "raanana",
  "kfar_saba",
  "hod_hasharon",
  "rosh_haayin",
  "modiin_illit",
  "other",
];

// Legacy: keep CITIES export for any places still using text values
export const CITIES = CITY_KEYS;